#include "headerConstants.h"

RowArray rowArrayBuilder(FILE *file, int *isValid);
void changeNameOfFile(char **pText);
char *copyToFirstFormat(char *text , char* format);
int isEndingWithColon(char *text);
int initializeRowsToZero(short **array, int length , int startIndex);
void removeUntilChar(char* text, char c);
int isStringContainOnlyLettersOrNumbers(char *text);
int isContainComma(char *copy);
int getNumber(char *text);
int isEmpty(char* text);
void deleteSpaces(char* text);
int isBeggingWithLetter(char *text);
Label initializeLabel(char* name , short rowNum , int isEntry , int isExtern);
int isStringEqual(char *text1 , char *text2);
char *copyString(char* text);
int getAmountOfBinaryRowsNeeded(char *row);
int isContainSpace(char *text);
void removeLeadingAndTrailingSpaces(char *text);
void printBinaryArrayToFile(FILE *file, BinaryArray binaryArray, int IC, int DC);
void printEntryToFile(FILE *file, LabelArray labelArray);
void printExternToFile(FILE *fileExt, ExternArray array);
void addToExternArray(Extern **pExternArray, char *name, short rowNum , int* length);
void printError(int errorValue);
void printWarning(int errorValue);
void printAllocationFailure();
void printFileOpenError();
void printArgumentMissing();
void freePointers(int sum , ...);
void printRedError();
void printYellowWarning();
void isAllocationSuccessful(int length , ...);
void printFileIsValid(char *);
void printFileMissing(char* name);
void closeAndFreeFiles(sourceFiles *files, int lengthBeforeAm);
void printAssembledFiles(sourceFiles *pFiles, int file);
void printFileIsNotValid(char *name);
