int firstPass(sourceFiles *file, BinaryArray *binaryMachineCodeTable, LabelArray *labelArray, RowArray *textTable);
int firstPassHelper(Row row, short **BinaryTable, int *arrayLength, Label **labels,
                    LabelArray *labelArray, int *isFileValid , int *isWarning);
int isLabelDeclaration(Row row);
int createEmptyBinaryRows(int oldLength,int toAdd ,short **binaryTable );
int isSyntaxValidFirstPass(char *row);
short addressCodeNum(char *operand);
int mightBeMcroOrLabel(char *text);
void getTwoOperand(char *row, short *binaryArray, int locationInTable);
void getOneOperand(char *row, short *binaryArray, int locationInTable);
void getZeroOperand(char *row, short *binaryArray, int locationInTable);
void insertIntoBinaryArray(int length, int add, char *row, short *binaryArray);
void guidanceAnalyze(char *row, int guid, int *Dc, char **string);
void addToLabelArray(Label **pLabel, Label label , int *length);
int isGuidance(char *row);
int analyzeDataGuidance(char *dataPart);
int analyzeStringLength(char *stringPart);
int isOperationSyntaxValidFirstPass(int opcValue, char *input, char *output);
void addOPCode(short OPCode,short *binaryArray);
void addOrigin(short origin,short *binaryCode);
void addDestination(short dest,short *binaryArray);
int fiveValidate(char *text);
int oneValidate(char *text);
int getOperationCodeValue(char *text);
int isLabelValid(char *name, Label *pLabel , int length);
int isGuidanceValid(char *row);
int isStringValid(char *text);
int isDataValid(char *text);
int isEntryValid(char *text);
int isExternValid(char *text);
int entryValidation(Label **pLabels, int length, char *name , int *isWarning);
